version: '3.1'

services:

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'fluxkart'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'Strangervk@18'
      MYSQL_ROOT_PASSWORD: 'Strangervk@18'
    ports:
      - '3306:3306'

  app:
    build: ..
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/fluxkart
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Strangervk@18
